import express from 'express';
import jwt from 'jsonwebtoken';
import Committee from '../models/Committee.js';
import User from '../models/User.js';
import Notification from '../models/Notification.js';
import { verifyToken } from './auth.js';

const router = express.Router();

// Get all committees for user
router.get('/', verifyToken, async (req, res) => {
  try {
    const committees = await Committee.find({
      members: req.userId,
      status: 'active'
    }).populate('createdBy', 'name phone');
    
    res.json(committees);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Create new committee - FIXED VERSION
router.post('/', verifyToken, async (req, res) => {
  try {
    const { name, nameUr, monthlyAmount, totalMembers, duration, language } = req.body;
    
    // Validate required fields
    if (!name || !monthlyAmount || !totalMembers) {
      return res.status(400).json({ error: 'Name, monthly amount, and total members are required' });
    }
    
    // Create committee (inviteCode will be auto-generated by pre-save hook)
    const committee = new Committee({
      name,
      nameUr: nameUr || name,
      monthlyAmount,
      totalMembers,
      duration: duration || totalMembers,
      createdBy: req.userId,
      members: [req.userId],
      status: 'active',
      language: language || 'ur',
      currentMonth: 1,
      payments: []
    });
    
    // Generate payments for all members for all months
    const payments = [];
    const totalDuration = duration || totalMembers;
    for (let month = 1; month <= totalDuration; month++) {
      payments.push({
        userId: req.userId,
        month: month,
        amount: monthlyAmount,
        dueDate: new Date(Date.now() + (month * 30 * 24 * 60 * 60 * 1000)),
        status: month === 1 ? 'pending' : 'pending'
      });
    }
    committee.payments = payments;
    
    // Set next payout date
    committee.nextPayoutDate = new Date(Date.now() + (totalDuration * 30 * 24 * 60 * 60 * 1000));
    
    await committee.save();
    
    console.log('✅ Committee created with invite code:', committee.inviteCode);
    
    // Create notification
    const notification = new Notification({
      userId: req.userId,
      type: 'committee_invite',
      title: 'Committee Created',
      titleUr: 'کمیٹی بن گئی',
      message: `Your committee "${name}" has been created successfully`,
      messageUr: `آپ کی کمیٹی "${nameUr}" کامیابی سے بن گئی`,
      relatedId: committee._id
    });
    await notification.save();
    
    res.status(201).json(committee);
  } catch (error) {
    console.error('Error creating committee:', error);
    res.status(500).json({ error: error.message });
  }
});

// Join committee with invite code
router.post('/join', verifyToken, async (req, res) => {
  try {
    const { inviteCode } = req.body;
    
    if (!inviteCode) {
      return res.status(400).json({ error: 'Invite code is required' });
    }
    
    const committee = await Committee.findOne({ 
      inviteCode: inviteCode.toUpperCase(),
      status: 'active'
    });
    
    if (!committee) {
      return res.status(404).json({ error: 'Invalid invite code' });
    }
    
    if (committee.members.includes(req.userId)) {
      return res.status(400).json({ error: 'Already a member' });
    }
    
    if (committee.members.length >= committee.totalMembers) {
      return res.status(400).json({ error: 'Committee is full' });
    }
    
    committee.members.push(req.userId);
    
    // Add payments for new member for remaining months
    for (let month = committee.currentMonth; month <= committee.duration; month++) {
      committee.payments.push({
        userId: req.userId,
        month: month,
        amount: committee.monthlyAmount,
        dueDate: new Date(Date.now() + (month - committee.currentMonth + 1) * 30 * 24 * 60 * 60 * 1000),
        status: 'pending'
      });
    }
    
    await committee.save();
    
    // Create notification
    const notification = new Notification({
      userId: req.userId,
      type: 'committee_invite',
      title: 'Joined Committee',
      titleUr: 'کمیٹی میں شامل ہوگئے',
      message: `You have joined ${committee.name}`,
      messageUr: `آپ ${committee.nameUr} میں شامل ہوگئے ہیں`,
      relatedId: committee._id
    });
    await notification.save();
    
    res.json(committee);
  } catch (error) {
    console.error('Error joining committee:', error);
    res.status(500).json({ error: error.message });
  }
});

// Mark payment
router.post('/:committeeId/pay', verifyToken, async (req, res) => {
  try {
    const { committeeId } = req.params;
    const { month } = req.body;
    
    const committee = await Committee.findById(committeeId);
    
    if (!committee) {
      return res.status(404).json({ error: 'Committee not found' });
    }
    
    const payment = committee.payments.find(
      p => p.userId.toString() === req.userId && p.month === month
    );
    
    if (!payment) {
      return res.status(404).json({ error: 'Payment not found' });
    }
    
    if (payment.status === 'paid') {
      return res.status(400).json({ error: 'Payment already made' });
    }
    
    payment.status = 'paid';
    payment.paidDate = new Date();
    payment.transactionId = `TXN_${Date.now()}_${Math.random().toString(36).substr(2, 6)}`;
    
    await committee.save();
    
    // Update user's trust score
    const user = await User.findById(req.userId);
    
    // Calculate trust score based on payment history
    const userPayments = committee.payments.filter(p => p.userId.toString() === req.userId);
    const paidPayments = userPayments.filter(p => p.status === 'paid');
    const newTrustScore = Math.min(100, Math.floor((paidPayments.length / userPayments.length) * 100));
    user.trustScore = newTrustScore;
    await user.save();
    
    // Create notification
    const notification = new Notification({
      userId: req.userId,
      type: 'payment_received',
      title: 'Payment Received',
      titleUr: 'ادائیگی موصول ہوگئی',
      message: `Payment of Rs. ${payment.amount} received for ${committee.name}`,
      messageUr: `${committee.nameUr} کی Rs. ${payment.amount} کی ادائیگی موصول ہوگئی`,
      relatedId: committee._id
    });
    await notification.save();
    
    res.json({ 
      success: true, 
      payment, 
      trustScore: user.trustScore,
      message: 'Payment recorded successfully'
    });
  } catch (error) {
    console.error('Error recording payment:', error);
    res.status(500).json({ error: error.message });
  }
});

// Get committee details
router.get('/:committeeId', verifyToken, async (req, res) => {
  try {
    const committee = await Committee.findById(req.params.committeeId)
      .populate('members', 'name phone trustScore')
      .populate('createdBy', 'name phone');
    
    if (!committee) {
      return res.status(404).json({ error: 'Committee not found' });
    }
    
    const userPayments = committee.payments.filter(
      p => p.userId.toString() === req.userId
    );
    
    res.json({
      ...committee.toObject(),
      userPayments
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

export default router;